name: Deploy to EC2 and Install Tomcat

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Ansible
      run: |
        pip install ansible
      working-directory: ${{ github.workspace }}

    - name: Configure AWS CLI
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region ap-south-1
      working-directory: ${{ github.workspace }}

    - name: Run Ansible Playbook
      run: ansible-playbook -i /github/workspace/playbook.yml
      working-directory: ${{ github.workspace }}
      env:
        ANSIBLE_HOST_KEY_CHECKING: False
