---
- name: Install Apache Tomcat on EC2 Instances
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Install AWS CLI
      apt:
        name: awscli
        state: present

    - name: Configure AWS CLI
      command: aws configure set aws_access_key_id YOUR_ACCESS_KEY && aws configure set aws_secret_access_key YOUR_SECRET_KEY && aws configure set region YOUR_REGION
      environment:
        AWS_ACCESS_KEY: YOUR_ACCESS_KEY
        AWS_SECRET_ACCESS_KEY: YOUR_SECRET_KEY
        AWS_REGION: YOUR_REGION

    - name: Fetch EC2 instances dynamic inventory
      command: aws ec2 describe-instances --query 'Reservations[].Instances[].[PublicIpAddress]' --output text
      register: ec2_instance_ip

    - name: Create Ansible inventory
      copy:
        content: |
          [ec2_instances]
          {% for ip in ec2_instance_ip.stdout_lines %}
          {{ ip }}
          {% endfor %}
        dest: /tmp/ec2_inventory
        mode: '0644'

    - name: Configure Tomcat
      hosts: ec2_instances
      become: yes
      tasks:
        - name: Update apt cache
          apt:
            update_cache: yes

        - name: Install Java
          apt:
            name: openjdk-8-jdk
            state: present

        - name: Download and extract Tomcat
          get_url:
            url: "https://archive.apache.org/dist/tomcat/tomcat9/v9.0.56/bin/apache-tomcat-9.0.56.tar.gz"
            dest: /tmp/tomcat.tar.gz

        - name: Extract Tomcat
          unarchive:
            src: /tmp/tomcat.tar.gz
            dest: /opt
            remote_src: yes
            owner: YOUR_USER
            group: YOUR_GROUP
            mode: 0755

        - name: Configure Tomcat
          template:
            src: /path/to/your/tomcat/conf/server.xml.j2
            dest: /opt/apache-tomcat-9.0.56/conf/server.xml
            owner: YOUR_USER
            group: YOUR_GROUP
            mode: 0644

        - name: Start Tomcat
          service:
            name: tomcat
            state: started

        - name: Enable Tomcat to start on boot
          service:
            name: tomcat
            enabled: yes
