name: 'Terraform AWS workflow'

on:
  workflow_dispatch:
    inputs:
      tfpath:
        description: 'Terraform Configuration Path'
        required: false
        default: 'aws_sample/create_ec2'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tf_code_check:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials Action For GitHub Actions
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ github.workspace }}/${{ github.event.inputs.tfpath }}

      - name: Terraform Validate
        run: terraform validate
        working-directory: ${{ github.workspace }}/${{ github.event.inputs.tfpath }}

      - name: Terraform Plan
        run: terraform plan
        working-directory: ${{ github.workspace }}/${{ github.event.inputs.tfpath }}

      - name: Terraform Destroy
        run: terraform plan -destroy
        working-directory: ${{ github.workspace }}/${{ github.event.inputs.tfpath }}


